### ISSUE TITLE
"Kin" definition ambiguous

### ISSUE THREAD

**Issue by cedwards57** [jProgr/TokiPonaDictionary#15]
Currently the definition of kin includes "indeed (emphasizes the word that follows)" and... according to most sources I can find, "kin" acts like a normal modifier word, which is to say, it emphasizes/applies to the word BEFORE it? So I'm not sure why the parentheses specification is necessary at all.

(Separate suggestion while I'm here: You could potentially include a "cont" definition for "kin" as well, as you should be able to use "kin la" to mean "additionally, likewise" (and I've seen it used this way); but that's maybe less of an 'official' use?)

**Comment by jProgr** [comment]
Hello. Thanks for pointing that out.

That meaning was taken from the book Toki Pona: The language of good - the simple way of life (2005) by B. J. Knight. Some examples from the source:
- pona! mi kin tawa ma Elopa - Cool! I also went to Europe.
- mi ken ala. mi kin moku - I can’t. I’m still eating.
- mi kin lukin e ona - I see it indeed.

I was checking the official book and in there the definition is not even separated from "a": "Particle: (emphasis, emotion or confirmation)". I couldn't find any examples mostly because it is a physical book.

On the book Toki Pona: The Simplest Language in the World (2019) by Robert Warnke the definition is: "adjective: indeed, still, too. kin can be the very last word in an adjective group. adverb: actually, indeed, in fact, really, objectively, kin can be the very last word in an adverb group. noun: reality, fact. interjection: really!". Under the section "Conjunctions and Temperature" the book states some examples and usage:
> The adjective kin is at the end of an adjective group and emphasizes it.
> jan pona mi kin li lon ni - My good friend is here.

Later:
<img width="561" alt="Screen Shot 2021-02-16 at 12 41 12" src="https://user-images.githubusercontent.com/2057224/108107014-49a44c00-7054-11eb-87cf-0ce22d43d558.png">

Notice the last sentence: The first source has it as "mi kin lukin e ona". But, as you stated, it is a modifier word and as such it affects the words before itself.

Taking the definition by Warnke and adapting it to this dictionary:
- kin:
  - mod: indeed, still, too, actually, in fact, really, objectively.
  - interj: really!
  - n: reality, fact.
  - cont: if reality, if fact.

What do you think? Do you have some sources for "additionally, likewise"?.

**Comment by cedwards57** [comment]
Oh, I see! Thank you for the info. I was mostly taking the "still, too, indeed" parts of the definition into account for the cont, as discussed <a href="https://rnd.neocities.org/tokipona/x1.html">here</a>-- I have yet to see examples of "kin" that use it as a mod to mean something like "objectively", are there examples of that?

My sources for the cont definition are mostly individual people: A discussion <a href="http://forums.tokipona.org/viewtopic.php?t=397">here</a> defines _kin la_ as "moreover, indeed":
![image](https://user-images.githubusercontent.com/32311207/108110619-87f43800-7061-11eb-985b-d0744b1afd59.png)

And an index of combined terms <a href="https://github.com/ttm/tokipona/blob/master/data/toki-pona_english.txt">here</a> defines _kin la_ as "moreover, in addition, likewise":
![image](https://user-images.githubusercontent.com/32311207/108110779-beca4e00-7061-11eb-819d-2b220000ab09.png)

And definitions listed on <a href="https://www.reddit.com/r/tokipona/comments/e0pvre/kinamute/">this Reddit discussion</a> and <a href="https://en.wiktionary.org/wiki/Appendix:Toki_Pona/kin">this Wiktionary article</a> also list the "too, even, indeed" definitions

So, while it might be less official, it seems less like the community at large doesn't tend to use it as a noun or to mean things like objectivity & fact, and more like... confirmation ("indeed") & emphasis (in the sense of "too" or "even")

My personal proposal would be something like:
- mod: also, too, still, really(?), even, indeed
- interj: really!, truly!, indeed!
- cont: moreover, indeed, in addition

(not including "likewise" because I think that is less common & is covered by "sama la" anyway)

Of course it is up to what you think is best / what best fits this dictionary, though! I'm just presenting this information for consideration.

Thank you!

**Comment by jProgr** [comment]
A lot of interesting information here :)

I will take note of the dates of the sources as it looks like the word seems to have evolved ever so slightly: Initially the word was a modifier and used with "la" as noted by the [forum conversation](http://forums.tokipona.org/viewtopic.php?t=397) on 2005, B. J. Knight on 2005. Then, for some reason, became indistinguishable from "a" as noted by _pu_ in 2014. Then, again, it came back to its sources as noted by [Renato Fabbri on 2016](https://github.com/ttm/tokipona/blob/master/data/toki-pona_english.txt), the [Wiktionary on 2017](https://en.wiktionary.org/w/index.php?title=Appendix:Toki_Pona/kin&oldid=42543042), a [Reddit conversation on 2019](https://www.reddit.com/r/tokipona/comments/e0pvre/kinamute/), Robert Warnke on 2019 with even more meanings.

It looks like it was just a change by Sonja Lang. The historical sources ([Moniz on 2020](https://docs.google.com/spreadsheets/d/1t-pjAgZDyKPXcCRnEdATFQOxGbQFMjZm-8EvXiQd2Po/edit#gid=1397008886) and [/dev/urandom on 2020](https://www.google.com/search?q=https://rnd.neocities.org/tokipona/x1.html&as_qdr=y15&safe=off&filter=0&biw=1440&bih=815&dpr=2)—as [image](https://user-images.githubusercontent.com/2057224/108128667-baf2f780-7072-11eb-9a05-7ae08dc9baf9.png)) also list "kin" as its own word with its own meanings.

I will add the definition as stated by you but I'll add and asterisk to it. But, you should know that this project is uncopyrighted (see [details](https://github.com/jProgr/TokiPonaDictionary/blob/master/LICENSE.md)) and any contribution will also become part of the public domain. Do you accept this?

Thank you very much.

**Comment by cedwards57** [comment]
I see! That's a good point, I wasn't paying enough attention to dates. Thank you for sorting out this information too!

If you feel it's appropriate, yes! Feel free to add my proposed contribution or any variant of it. Thank you for making such a useful tool for the language!
